### ISSUE TITLE
New URL: Reolink App

### ISSUE THREAD

**Issue by tumtumsback** [bhagyas/app-urls#25]
Hi! The url to open the Reolink app is fb1675493782511558://

**Comment by Casper-O** [comment]
Do you by any chance know how to open up a specific camera ?

**Comment by tumtumsback** [comment]
I don't -- if you can figure it out, please update here!

**Comment by Casper-O** [comment]
I had some talk eith Reolink support - they say its not possible, but i still Think it is.

Sadly i am not able to look deeper into it myself

**Comment by bhagyas** [comment]
Thank you! Added.
